### ISSUE TITLE
sass-lint was abandoned 5 years ago

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/webpack-config#69]
We have an ancient version of sass-lint in `@silverstripe/webpack-config` which triggers dependabot alerts due to some of its own dependencies, which is annoying because it's only a dev dependency so there's no risk to production sites.  sass-lint was abandoned 5 years ago, we're already on the latest version of it

We should migrate to something else, probably [stylelint](https://github.com/stylelint/stylelint)

## Acceptance criteria
- CMS 5 webpack config is updated to use a supported library to lint its stylesheets.
- CMS 5 eslint config is updated to use a supported library to lint its stylesheets.
- CMS 5 supported modules are updated to use the latest version of our cms 5 webpackconfig and eslint config.
- Any linting change are addressed to make sure the builds are green

## Related
- https://github.com/silverstripe/silverstripe-admin/issues/1437

## PRs
- https://github.com/silverstripe/webpack-config/pull/71
- https://github.com/silverstripe/eslint-config/pull/22
- https://github.com/silverstripe/eslint-config/pull/23
- https://github.com/silverstripe/silverstripe-admin/pull/1727
- https://github.com/silverstripe/silverstripe-elemental-bannerblock/pull/141
- https://github.com/silverstripe/silverstripe-asset-admin/pull/1454
- https://github.com/silverstripe/silverstripe-cms/pull/2929
- https://github.com/silverstripe/silverstripe-blog/pull/752
- https://github.com/silverstripe/silverstripe-contentreview/pull/229
- https://github.com/silverstripe/silverstripe-campaign-admin/pull/299
- https://github.com/silverstripe/silverstripe-login-forms/pull/171
- https://github.com/silverstripe/silverstripe-segment-field/pull/105
- https://github.com/silverstripe/silverstripe-linkfield/pull/277
- https://github.com/silverstripe/silverstripe-userforms/pull/1282
- https://github.com/silverstripe/silverstripe-sharedraftcontent/pull/230
- https://github.com/silverstripe/silverstripe-elemental/pull/1173
- https://github.com/bringyourownideas/silverstripe-maintenance/pull/217
- https://github.com/symbiote/silverstripe-advancedworkflow/pull/525
- https://github.com/colymba/GridFieldBulkEditingTools/pull/275
- https://github.com/silverstripe/silverstripe-admin/pull/1731
- https://github.com/silverstripe/silverstripe-contentreview/pull/230
- https://github.com/silverstripe/silverstripe-login-forms/pull/172

## NEW PRs
- https://github.com/silverstripe/silverstripe-mfa/pull/535
- https://github.com/silverstripe/silverstripe-session-manager/pull/188
- https://github.com/silverstripe/silverstripe-tagfield/pull/285
- https://github.com/silverstripe/silverstripe-totp-authenticator/pull/151
- https://github.com/silverstripe/silverstripe-webauthn-authenticator/pull/175
- https://github.com/silverstripe/silverstripe-externallinks/pull/123
- https://github.com/silverstripe/silverstripe-frameworktest/pull/173
- https://github.com/silverstripe/silverstripe-gridfieldqueuedexport/pull/103
- https://github.com/silverstripe/silverstripe-lumberjack/pull/143
- https://github.com/silverstripe/silverstripe-realme/pull/136
- https://github.com/silverstripe/silverstripe-subsites/pull/566

### Additional task
- https://github.com/silverstripe/.github/issues/228

### Note 
Disabled rules were excluded according to the principle that the more errors, the greater the likelihood that this rule was not previously supported in the module. But they still require review in each module.

**Comment by maxime-rainville** [comment]
Random questions:
- I'm assuming this can be done in a minor since those are dev dependencies?
- Do we know why this wasn't flag in our CMS 5 dependency upgrades?

**Comment by emteknetnz** [comment]
- It's only dev dependencies so I think it could probably be done in a patch
- I don't know why it wasn't flagged in CMS 5 dep upgrades

**Comment by maxime-rainville** [comment]
Guy says: We did catch it, but decided it didn't matter. We're just fixing this now to shut up the dependabot alerts.

**Comment by GuySartorelli** [comment]
@sabina-talipova Some PRs are failing the JS CI run (I suspect most if not all of them are just slight copy/paste errors in the package.json scripts) - but a lot of them have code being ignored which I didn't expect. I haven't commented on all of them, we can discuss them all together in https://github.com/silverstripe/silverstripe-elemental-bannerblock/pull/141#discussion_r1580185222

**Comment by GuySartorelli** [comment]
PRs merged

**Comment by sabina-talipova** [comment]
I reopen it, since I missed some modules.

**Comment by emteknetnz** [comment]
All merged and merged-up
